version: '3'

services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: django
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: django
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql/logs:/var/log/mysql
      - ./mysql/data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
    links:
      - db
    ports:
      - 8080:80
    depends_on:
      db:
        condition: service_started
  web:
    build: .
    entrypoint: [ 'dockerize', '--timeout', '60s', '--wait', 'tcp://db:3306' ]
    command: ["python", "manage.py", "runserver", "0.0.0.0:8001"]
    volumes:
      - .:/code
    ports:
      - 8002:8001
    depends_on:
      db:
        condition: service_started
